### ISSUE TITLE
Eliminate overlap between session's attributes: memory handler and callstack

### ISSUE THREAD

**Issue by miloszm** [dusk-network/piecrust#123]
#### Summary
In current piecrust implementation, memory handler (MemoryHandler) maintains a map of per-module-id memories (Linear), while call stack (CallStack) maintains a map of per-module-id instances (wasmer::instance via WrappedInstance). Both MemoryHandler and CallStack are attributes of a Session. This is suboptimal, as both maps perform the same state logic on structures which partly overlap. It is potentially dangerous as the overlap is not explicit. Should future maintainers un-sync the state logic of both maps, not easy to diagnose memory problems could start re-occurring. Hence, it is important to make the overlap explicit and maintain only a single map so that for a given module id it is obvious which memory and which instance belong to it.

#### Possible solution design or implementation
Merge maps from MemoryHandler and from CallStack together, create an object that will encompass Linear and wasmer::Instance. Perform ripple effect and follow-up refactorings, so that the number of concepts is minimized and non-overlapping.

#### Additional context
The duplication described above was a cause of a hard-to-detect bug, hence it ought to be a high priority to eliminate it explicitly.

**Comment by ureeves** [comment]
`MemoryHandler` is no longer present. Closing
