### ISSUE TITLE
Automatic Module Redeployment after Session Restore

### ISSUE THREAD

**Issue by miloszm** [dusk-network/piecrust#144]
#### Summary
Information about which modules were deployed by the session is currently lost after the session is committed and destructed. When session is restored from a commit, user needs to manually deploy necessary modules. Automatic mechanism for redeployment is needed so that after restore the user of a session operate as if the session was not stored and restored.

#### Possible solution design or implementation
Modules' bytecode need to be stored along with the commit data. The design and details of the solution needs to be elaborated and is part of this issue's scope. 

#### Additional context
Solution may involve introduction and use of a database in Piecrust. Modules' bytecode could be kept within the database together with the other commit data.

**Comment by ureeves** [comment]
This issue may also be solved by the simplest module deployment mechanism. It would be much simpler to keep bytecode at the top level, rather than at commit level, even if it is not technically correct.
I suggest that be fixed once #145 is tackled.
