### ISSUE TITLE
Switch diffing implementation to qbsdiff

### ISSUE THREAD

**Issue by miloszm** [dusk-network/piecrust#150]
Crate bsdiff is not reliable and we need to switch to qbsdiff.

Crate bsdiff when diffing displays the following behavior:

`thread 'session_commits_persistence' has overflowed its stack`

this is happening when buffers compared have following characterisics:
length of both: 327680
number of zeroes in both: 327146
number of different bytes: 2
positions of different bytes: 66250, 327676
contents of differing bytes: 17 vs 18, 17 vs 18

Crate qbsdiff works correctly in the above scenario, hence it is desirable to switch to qbsdiff.

**Comment by ureeves** [comment]
Closed by #151
