### ISSUE TITLE
Provide coverage for non-unique diffed module commit ids

### ISSUE THREAD

**Issue by miloszm** [dusk-network/piecrust#152]
#### Summary
Rusk's wallet_grpc test provides a scenario in which module commit ids are appearing repeatedly in a commit history. This requires diffed commits to be stored independently in the presence of multiple repeating ids and not overwrite each other.

#### Possible solution design or implementation
The implementation requires introducing a diff commit file naming scheme that is not mapped 1-1 with commit ids.

#### Additional context
The functionality needs to be performant in the presence of a large number of commits (say 200-1000). In addition, it will have impact in potential commit cut-off or squash schemes.

**Comment by ureeves** [comment]
The conflict referenced is impossible since the introduction of the `ModuleStore`.
