### ISSUE TITLE
Ownership of Contracts

### ISSUE THREAD

**Issue by miloszm** [dusk-network/piecrust#158]
#### Summary
We need to support the concept of contract ownership. 
Ownership of a contract may help deciding who is allowed to execute certain contract methods.

#### Possible solution design or implementation
Ownership information is passed via constructor arguments and maintained by contract.

#### Additional context
Contract ownership should be passed to a contract that is deployed (instantiated) by a given contract.

Rename host_data to meta_data, don't panic if it does not exist, return option.
Identifier needs to be accessible in the top level transaction and the transactions initiated by it.
Identifier is a hash of a module id and its byte-code. From the point of view of Piecrust, this so called instance identifier is an opaque object which will only be compared but nothing needs to be known about its internal structure.

Related to issue #93

**Comment by miloszm** [comment]
Implementation for this issue is covered by the implementation for issue #167.

**Comment by ureeves** [comment]
Close by https://github.com/dusk-network/piecrust/pull/180
