### ISSUE TITLE
Secure Persistent Metadata for Contracts

### ISSUE THREAD

**Issue by miloszm** [dusk-network/piecrust#167]
#### Summary
For contracts attributes such as contract's owner or contract's SELF_ID we need the ability of storing and accessing such attributes on a per module (contract) basis. A set of such attributes constitute contract's metadata. Distinguishing feature of contract's metadata is that it is managed by the VM and from the point of view of the contract it is immutable. Another way to look at it is that metadata constitutes a context for the contract.

#### Possible solution design or implementation
We store contract's metadata in a file in a similar manner to how object code is stored.

#### Additional context
This issue is related to issue #158 (ownership of contracts) which requires storing of contract's owner.

**Comment by ureeves** [comment]
Closed by https://github.com/dusk-network/piecrust/pull/180
