### ISSUE TITLE
Better structure and data encapsulation

### ISSUE THREAD

**Issue by ureeves** [dusk-network/piecrust#181]
#### Summary
In the context of implementing #180 (Issue #167), we have noticed that there are several concepts that can be grouped together in particular ways to better structure the project, reduce the maintenance burden, and aid in the development of new features.

In particular, there seem to be at least three different categories of data:

- Module data. This is data that is set at module deployment time, and never changes in the lifetime of the module. Examples are:
    - Constructor data (transient/not persisted)
    - Ownership data
    - Self ID

An API should be exposed that hints at, or even enforces, that these things cannot be changed for the lifetime of the module, possibly at deploy time.

- Session data. This is data that is set at the beginning of the session, and never changed for its duration. Examples include:
    - What is currently called `SessionMetadata` - contains universal settable map containing context items like 'height' 

In the same way as before, an API should be exposed that hints, or enforces, that these pieces of data are set at the beginning of a session, possibly during instantiation.

- Call data. This is data that is set at the beginning of a call to `transact` or `query`. This is data such as:
    - (Gas) limit
    - Sender (same entity as Ownership)

This should be set when a call is performed.

#### Possible solution design or implementation
A clear solution would be to give each of these structs, and allow them to be set only during the appropriate time:

```rust
struct ModuleData {
    pub self_id: Option<ModuleId>,
    pub constructor: Option<?>,
    pub owner: [u8; 32],
}

impl Session {
    fn deploy(bytecode: &[u8], data: ModuleData) {
        // ...
    }
}

struct SessionData {
    map: Map// some map from string to `Vec<u8>`
}

impl VM {
    fn session(root: [u8; 32], data: SessionData) -> Session {
        // ...
    }
}

struct CallData {
    pub limit: u64,
    pub sender: [u8; 32],
}

impl Session {
    fn transact<Arg, Ret>(module_id: ModuleId, method: &str, arg: Arg, data: CallData) -> Ret {
        // ...
    }
}
```

It is important to note that both the API and the structures outlined here are mere suggestions, and it is up to the implementer to best structure this.

**Comment by miloszm** [comment]
It looks like module data has a proper API already, it can be set only via the `deploy` call and it is read-only after a module is deployed. It is different with session data - API allows for setting it any time so this part needs work - elimination of the `set_meta` call and extending the session creation API with the possibility of passing session data which would, after session creation, be only accessible as read-only data.

**Comment by miloszm** [comment]
Implementation of module data and session data related changes is in PR #185. Implementation of CallData related changes is in branch `structure-improv-call-data-181`, for easier review.
