### ISSUE TITLE
Implement Missing Tests

### ISSUE THREAD

**Issue by miloszm** [dusk-network/piecrust#184]
#### Summary
> 💡 Part of Piecrust functionality remains untested or it is only indirectly tested. Add more direct tests, especially concerning module deployment, ownership, metadata, persistence, commits.

#### Possible solution design or implementation
Use unit tests and test contracts to develop more tests. Enrich this description with a list of tests to implement first.

**Comment by autholykos** [comment]
This issue is too generic. Closing to de-clutter the board
