### ISSUE TITLE
Proc Macro for `uplink::wrap_call`

### ISSUE THREAD

**Issue by HDauven** [dusk-network/piecrust#308]
#### Summary

Every function a contract developer wants to expose to external callers requires a wrapper function to `uplink::wrap_call` for the internal function:

```rust
impl Counter {
    /// Read the value of the counter
    pub fn read_value(&self) -> i64 {
        self.value
    }

    /// Increment the value of the counter by 1
    pub fn increment(&mut self) {
        let value = self.value + 1;
        self.value = value;
    }
}

/// Expose `Counter::read_value()` to the host
#[no_mangle]
unsafe fn read_value(arg_len: u32) -> u32 {
    uplink::wrap_call(arg_len, |_: ()| STATE.read_value())
}

/// Expose `Counter::increment()` to the host
#[no_mangle]
unsafe fn increment(arg_len: u32) -> u32 {
    uplink::wrap_call(arg_len, |_: ()| STATE.increment())
}
```

#### Possible solution design or implementation

We can hide this implementation detail by introducing a procedural macro that a function can be annotated with to expose it to external callers:
```rust
#[contract]
impl Counter {
    /// Read the value of the counter
    pub fn read_value(&self) -> i64 {
        self.value
    }

    /// Increment the value of the counter by 1
    pub fn increment(&mut self) {
        let value = self.value + 1;
        self.value = value;
    }
}
```

**Comment by ZER0** [comment]
As discussed previously, I'm against having macros (I derive this attitude from my time in Mozilla where at the office the rust team had a poster about it).
If it makes sense, we could improve the API, but at least for the time being we should not include any macros in the VM crate (we will tackle this once we're open to 3rd party contracts).

Said that, you're more than welcome to create a separate crate / repository that expose such functionality – and therefore can be used to create contracts – that you can improve and work over time, maybe with some other functionalities / tools too, without impact directly the upstream of piecrust.
