### ISSUE TITLE
Add ability to migrate contract bytecode

### ISSUE THREAD

**Issue by ureeves** [dusk-network/piecrust#313]
#### Summary
In the interests of allowing the Dusk protocol to be upgradable, and given that part of the protocol is expressed in smart contracts, it becomes necessary to be able to swap a contract's bytecode for another. Since the new contract might, and probably will, expect a different memory layout than the old contract, a migration procedure for the memory of the contract should also be supported.

This migration procedure is by its nature a destructive operation in terms of the memory of the contract, but may also have consequences for contracts depending on the one being migrated. If the contract changes its externally available API in any way, all contract's that call it should be considered invalid.

#### Possible solution design or implementation
The way to do this might be in the context of a `Session`, introducing a new public function - say `Session::migrate` - taking a contract ID, the new bytecode, and a closure specifying how to migrate from the current memory state to the new state. The arguments to this closure should likely be a handle to instances of both contracts, allowing for several operations to be performed.

```rust
impl Session {
    pub fn migrate<F>(&mut self, contract_id: ContractId, new_bytecode: &[u8], closure: F)
    where
        F:  FnOnce(ContractHandle, ContractHandle) -> Result<()>
    {
         // ...
    }
}
```

**Comment by ureeves** [comment]
> This looks good, how about adding a `dry_run` boolean parameter, so that it is possible to call this method and check if everything is ok? Also, if `dry_run=false`, I'd automatically remove the first contract, in order to prevent the migration from running again.

I understand the spirit of this. Luckily the very concept of a `Session`, together with being able to commit it or not, and us being able to start a new session from before the migration started at any time (rollback), this should not be necessary.

Unless you're talking about checks that should be performed by this function. If so, could you elaborate on what you mean?

**Comment by miloszm** [comment]
Indeed, not committing session solves part of it, but still, we could have custom checks inside of the closure, but I guess there is nothing that session and rollback cannot do, still, it could be more efficient to be able to dry run, and more manageable, esp. if we migrate many contracts, say in a batch. Just sth. to consider.
