### ISSUE TITLE
Audit: too much gas for feeder calls

### ISSUE THREAD

**Issue by ureeves** [dusk-network/piecrust#344]
#### Summary

Currently a feeder call is performed with the maximum amount of gas possible. This is ok for contracts that the host controls, but may become a problem for contract it does not. If a contract is malicious it may simply loop forever, and never provide any data, and effectively allow the chain to be DOSed.

https://github.com/dusk-network/piecrust/blob/a6814919dc20347dc1571ec64db04e72056b8e31/piecrust/src/session.rs#L486

#### Possible Solution (Optional)

Allow the caller to determine the gas with which the feeder call can be executed with.

**Comment by ureeves** [comment]
I'm not sure what you mean by "specified in the session". There is no session-bound gas limit. All gas limits are given with each call, this was the only exception.

**Comment by herr-seppia** [comment]
Sorry, I was too focus on the consumer side (`rusk`)

> This is ok for contracts that the host controls, but may become a problem for contract it does not

About this, is it ok to say that the only way to call a contract without the "host" controls is to call it with an ICC? 
If so, the gas limit will be specified by the parent call, so even if the malicious contract will specify u64::MAX it will be constraint by the ICC gas limit

Or are you thinking to a different and/or more generic use case?

**Comment by ureeves** [comment]
> Sorry, I was too focus on the consumer side (`rusk`)
> 
> > This is ok for contracts that the host controls, but may become a problem for contract it does not
> 
> About this, is it ok to say that the only way to call a contract without the "host" controls is to call it with an ICC? If so, the gas limit will be specified by the parent call, so even if the malicious contract will specify u64::MAX it will be constraint by the ICC gas limit
> 
> Or are you thinking to a different and/or more generic use case?

A contract calling a feeder call through an ICC will result in a panic, so we only need to worry about the host calling the contract. When third-party contracts become allowed, we can't trust that giving limitless funds to it is safe, so we should probably limit setting infinite gas to the genesis contracts (contracts we control).
