### ISSUE TITLE
Introduce concept of "dirty" for the world scope and per-module scope

### ISSUE THREAD

**Issue by miloszm** [dusk-network/piecrust#39]
**Describe what you want implemented** 
At any time we should be able to know if the global or "world" state, as well as per-module states, are "dirty", i.e., their memory have been modified since the last snapshot. 

**Describe "Why" this is needed**
We need to know when taking a new snapshot is really needed and when it is superfluous, this applies both to the world and module scopes.

**Describe alternatives you've considered**
Alternative is to always take snapshots, but it is much less efficient.

**Additional context**
"dirty" detection is not trivial and may start with simple treating of every transaction as "dirtying", and end with using special API provided by Wasmer, and various levels of sophistication in between. Taking snapshot clears the "dirty" flag for the corresponding scope.

**Comment by ureeves** [comment]
This is definitely no longer applicable
