### ISSUE TITLE
Construct a tree from module memories

### ISSUE THREAD

**Issue by ureeves** [dusk-network/piecrust#55]
**Describe what you want implemented**
One of the most important features the VM should provide is the so called "state root". The state root is the root of a [Merkle tree](https://en.wikipedia.org/wiki/Merkle_tree), where the leaves of the tree are the hashes of the bytecode of the module and its linear memory.
This root changes across snapshots, and would - optionally - make a great `SnapshotId`.

**Describe "Why" this is needed**
To ensure each participant in the blockchain can efficiently verify the state of their VM is the same as all other participants, the state root is included in a block. It is, therefore, a requirement.

**Describe alternatives you've considered**
An alternative way of providing such a state root would be to hash all modules sequentially. This is, however, computationally prohibitive for a large set of modules. I would also make make efficient inclusion proofs impossible.

**Additional context**
If `ModuleId` is used to determine the position in the tree, this tree will likely be quite sparse. The implementer will have to decide what the most sensible way to populate the tree for both computational and spatial efficiency.

**Comment by miloszm** [comment]
Implementation details:

Every session commit should change the value of the root, 
the root is re-calculated at commit time as follows:

**root = merkle root of a tree whose leaves are taken from the following set:**

**all "last" commits of all modules persisted at a given VM base directory**

Having a set of "last" commits at a given time, say: set S, we order S numerically by module id,
in the ascending order, and obtain an S' to be our set of merkle leaves. Then we proceed with a standard procedure
of calculating the merkle root if a given set of leaves.
Each leaf is a hash of module's memory contents, which is the same as ModuleCommitId if a given commit.
