### ISSUE TITLE
Module constructors

### ISSUE THREAD

**Issue by ureeves** [dusk-network/piecrust#93]
#### Summary
There should be a way to provide modules some data on deployment, which is then used to initialize the state. Currently it is only possible to "bake in" the initial state in the WASM bytecode. This precludes the module writer from writing a module once, and then reusing the same bytecode with different initial states. This use-case should become possible.

#### Possible solution design or implementation
It could be possible to check the existence of a such a module constructor by interpreting the module exports. If an export exists with a predefined name and signature, this could then be called with a piece of data provided by the deployer through the argument buffer. An example name and signature could be:

```rust
#[no_mangle]
fn ctor(pos: i32) {
    // ...
}
```

The `pos` argument would be the length of the argument in the buffer. The contract would then deserialize (possibly using `rkyv`) the piece of data and proceed with initialization.

This **has** to be accompanied with a mechanism that disallows the constructor to be called more than once.

#### Additional context
Not only is this a useful mechanism for prospective smart contract writers, it's also extremely useful to construct multiple networks with different types of genesis data, given that different networks are defined by differently initialized genesis contracts.

**Comment by miloszm** [comment]
name should be `new` or `instantate`, arguments  are optional

**Comment by ureeves** [comment]
Closed by https://github.com/dusk-network/piecrust/pull/168
